[MAIN]
customPaths = False

[praSUBCATCHMENTS]
streamThreshold = 500
minLength = 100
smoothingWindowSize = 5
weightedSlopeFlow = False


[praPROCESSING]
minDirectNeighborsPass1 = 3
minDiagonalNeighborsPass2 = 2
outputCompression = LZW
maskNoDataValue = 0


[praSEGMENTATION]
# minimum, maximum area [m²] to assign avalanche size to PRAs
sizeClass1 = 0,500
sizeClass2 = 500,2500
sizeClass3 = 2500,12500
sizeClass4 = 12500,62500
sizeClass5 = 62500,inf
sizeFilter = 500


[praASSIGNELEV]
elevationBand1 = 0,1800
elevationBand2 = 1800,2000
elevationBand3 = 2000,2200
elevationBand4 = 2200,2400
elevationBand5 = 2400,5000


[praPREPFORFLOWPY]
assignElevSize = False
compressOutputs = True
# PRA vectorization/rasterization modes
enableRasterizePRA = True
rasterizeModePRA = attribute
# ID vectorization/rasterization modes
rasterizeAttributePRA = praAreaM
enableRasterizeID = True
rasterizeAttributeID = praID
# calculate boundaries for FlowPy efficiency
deriveBoundaries = False

# Results to size
resParamsToSize =

# snow climate (not used ATM)
D0 = 0
deltaD = 0.001
constantTemperature = True
Tcons = -11
T0 = 0
deltaT = -0.01
TCold = -11
TWarm = -1
