# Configuration settings for the autoATES classifier

[FLAGS]
forestReclassficationInRunout = False

[PARAMETERS]
# Moving window size to smooth slope angle layer for calcuation of Class 4 extreme
WIN_SIZE = 1

# --- Define slope angle Thresholds
# Class 0 / 1 Slope Angle Threshold (Default 15)
SAT01 = 0

# Class 1 / 2 Slope Angle Threshold (Default 25)
SAT12 = 28

# Class 2 / 3 Slope Angle Threshold (Default 40)
SAT23 = 39

# Class 3 / 4 Slope Angle Threshold (Default 45)
# This is calculated on a smoothed raster layer, so the slope angle value is not representative of real world values
SAT34 = 45

# --- Define alpha angle thresholds
# Class 1 Alpha Angle Threshold (Default 18)
AAT1 = 18

# Class 2 Alpha Angle Threshold (Default 25)
AAT2 = 26

# Class 3 Alpha Angle Threshold (Default 38)
AAT3 = 36

# CROWNCOVER Values
# --- Add tree coverage criteria
# Tree classification: "open" (upper bound)
TREE1 = 10

# Tree classification: "sparse" (upper bound)
TREE2 = 25

# Tree classification: "mixed" (upper bound)
TREE3 = 65

# Forest interaction
# numbers of forested cells that are hit by the path before
FORESTINT1 = 1
FORESTINT2 = 8

# --- Threshold for size of clusters to be removed (generalization)
ISL_SIZE = 1000

CONNECTIVITY = 1


[PATHS]
# if customPaths is True, the paths to the rasters need to be provided below
# if customPaths is False, the Avaframe structure is used
customPaths = False

# --- Set Working Directory
wd = /home/paula/data/ConnaugtCreek_ATES/10m/ATES_size5/test

# --- Set Input Files
DEM = /home/paula/data/ConnaugtCreek_ATES/10m/Inputs/DEM_10m.tif

canopy = /home/paula/data/ConnaugtCreek_ATES/10m/Inputs/RES/forest_canopy_10m.tif

forest_int =

FP = /home/paula/data/ConnaugtCreek_ATES/10m/FINAL/maxSize5/01_com4FlowPy/Outputs/com4_aca3232100_20260610_120816_fpTravelAngleMax.tif

SZ = /home/paula/data/ConnaugtCreek_ATES/10m/FINAL/maxSize5/01_com4FlowPy/Inputs/REL/pra030secN-0000-5000-5-praAreaM.tif

#Glacier rasterized glacier outlines from 2015 - 1: glacier 0; no glacier
#glacier='/home/christoph/Documents/1_ATES/DATA/GLETSCHER/glacier.tif'
