[GENERAL]

# The simulation hash of the simulation that is analysed
# If only one results folder with a simhash exists, this is used.
simHash =

# Module name of the simulation that is analysed (the analysis is tested for com4FlowPy)
modName = com4FlowPy

# column and row number (x and y  coordinate of raster) of the starting cell of the thalweg/path
# if (startRow or startCol) and relId is empty, for all thalwegData (with relating center of variable) are plotted
startRow =
startCol =
relId =

# output variable that is plotted (of whole simulation)
plotVariable = zdelta
# which center of is used
# possible:CoF (center of flux, default), CoZd (center of zdelta), CoE(center of energy)
# if empty all files are plotted
centerOfVariable = CoF

# If True, all thalwegs are represented in the field plot (upper panel)
thalwegPra = True
colorPra = 6900D1

# Avalanche size is only for the plot title
avalancheSize =

# variable that is used for statistic boxplots over all thalwegs
# possible: travelLengthMax, velocity, impressure, (the extended values within the process path are used)
# travelLengthAveraged, velocityAveraged, impressureAveraged, zdeltaAveraged (averaged values are used: without thalweg extension)
# alphaIn, velocityMaxIn, zdeltaMaxIn  (the input data)
# relArea (areas of release areas)
# "averaged" means that the averaged thalweg values are used (not read from raster along thalweg)
statisticVariable = travelLengthMax

# if plotLogScale is True the y axis of the statistic boxplots is logarithmic
plotLogScale = False

# if plotAllThalwegLocations is True or plotThalweg2D is True,
#choose if the extended thalwegs or the aeraged thalwegs are plotted
2DExtendedThalwegs = True

# if averagedZdelta is True, for thalweg data the averaged values are used for zdelta (and velocity and impact pressure)
# if averagedZdelta is False, the data is read from the result zdelta raster
# (be aware that this is the maximum of all overlayed flow paths)
averagedZdelta = True

# density of avalanche (used for computing impact pressure) in kg/m³
rho = 200

boxplotYlimMin =
boxplotYlimMax =

[FLAGS]
# flags which plots should be saved:
plotStatisticBoxplot = True
plotStatisticScatterPlot = True
plotAllThalwegLocations = True
# these plots are done for each thalweg
plotThalwegLocation = False
plotThalweg2D = False
plotThalwegAltitude = False


[SIZECLASS]
# colors for the sizes
colorSize1 = 0096FF
colorSize2 = 00FF00
colorSize3 = FFD500
colorSize4 = FF0000
colorSize5 = AA00FF

# boundaries for sizes
# ------ technical scheme ---------------
# for runout length [m] - technical scheme
travelLengthSize1Max = 49
travelLengthSize2Max = 248
travelLengthSize3Max = 837
travelLengthSize4Max = 1883

# for impact pressure [kPa] - technical scheme
impressureSize1Max = 18
impressureSize2Max = 56
impressureSize3Max = 178
impressureSize4Max = 562

# for release area [m²] - technical scheme
relAreaSize1Max = 500
relAreaSize2Max = 2500
relAreaSize3Max = 12500
relAreaSize4Max = 62500

# ------ communication scheme ---------------

# for runout length [m] - communication scheme
travelLengthSize1MaxCom = 50
travelLengthSize2MaxCom = 250
travelLengthSize3MaxCom = 750
travelLengthSize4MaxCom = 2000

# for impact pressure [kPa] - communication scheme
impressureSize1MaxCom = 20
impressureSize2MaxCom = 50
impressureSize3MaxCom = 200
impressureSize4MaxCom = 500

# for release area [m²] - communication scheme
relAreaSize1MaxCom = 500
relAreaSize2MaxCom = 2500
relAreaSize3MaxCom = 12500
relAreaSize4MaxCom = 62500


[ana5Utils_DFAPathGeneration_override]
# use default com1DFA config as base configuration (True)
# if False and local is available use local
defaultConfig = True

# extension method at the top
# option 0: take the highest particle in the release
# option 1: find the point that will lead to the longest runout
# option 2: find path depending on flow direction
extTopOption = 2

# the path extracted from the DFA simulation is re-sampled
# re-sampling step size is defined resampleDistance = nCellsResample x cellSize)
nCellsResample = 2
# Degree of the spline for splprep.
kResample = 1

# when extending the path at the bottom, extend path in
# the direction extracted form the last points of the path
# (all points at a distance nCellsMinExtend x cellSize < distance < nCellsMaxExtend x cellSize
# from the end)
nCellsMinExtend = 4
nCellsMaxExtend = 10
# this value needs to be chosen in accordance with nCellsResample (if nCellsMaxExtend < nCellsResample no points
# might be found for the path extension process)

# for the extrapolation at the bottom, add factBottomExt * sMax to the path (and then check if the extension
# is on the DEM, if not iterate by dichotomy until we find a point on the topography or reach a maximum
# iteration number (integer, in this case we pick the last point found inside the dem)
# or precision (nBottomExtPrecision * cellSize))
factBottomExt = 0.3
maxIterationExtBot = 10
nBottomExtPrecision = 10

