
[GENERAL]
# if runFlowPy is True, pra Delineation and FlowPy are run.
# if runFlowPy is False, pra Delineation and FlowPy are skipped and only thalweg extension and analysis are computed
runFlowPy = True

[mod1Release_praDelineationVeitinger_override]
# use default praDelineation config as base configuration (True) and override following parameters
# if False and local_praDelineationVeitinger is available use local
defaultConfig = True

# if customPaths is True, the paths to DEM and forest are provided directly
# if customPaths is False, the files are provided in the AvaFrame structure
customPaths = False

forestType = pcc
saveAllThresholds = False
singleThreshold = 0.30
radius = 6
prob = 0.5
winddir = 0
windtol = 180


[mod1Release_mod1Release_override]
# use default mod1Release config as base configuration (True) and override following parameters
# if False and local_mod1Release is available use local
defaultConfig = True

streamThreshold = 500
minLength = 100
smoothingWindowSize = 5
weightedSlopeFlow = False

minDirectNeighborsPass1 = 3
minDiagonalNeighborsPass2 = 2
outputCompression = LZW
maskNoDataValue = 0


[mod2Mobility_compParams_override]
# use default parameterization config as base configuration (True) and override following parameters
# if False and local_compParams is available use local
defaultConfig = True

# Rel vol size dependent parametrization for
# > dry:
sizeMax = 5
alphaSize2 = 32
deltaAlpha = 3
uMaxSize2 = 20
deltaUMax = 15
constantExp = True
constantExpValue = 12
constantPraThickness = True
praThickness = 1

# Rel vol size dependent parametrization shift for
# > wet:
alphaDependendTemperature = True
sizeShiftAlpha = 0.5
sizeShiftUmax = -0.75
sizeShiftExp = 12

# Results to size
resParamsToSize =

# snow climate (not used ATM)
D0 = 0
deltaD = 0.001
constantTemperature = True
Tcons = -11
T0 = 0
deltaT = -0.01
TCold = -11
TWarm = -1


[com4FlowPy_com4FlowPy_override]
# use default com4FlowPy config as base configuration (True) and override following parameters
# if False and local_com4FlowPyCfg is available use local
defaultConfig = True
#++++++++++++ Flow-Py Model Parameters
# alpha:
# Angle-of-reach Alpha [°] - defines max. longitudinal runout limit
# equivalent to a Coulomb-friction of tan(alpha) in a sliding block model
#---------------------
# exp:
# Spreading Coefficient (influences lateral spreading)
#---------------------
# flux_threshold:
# Flux threshold (influences lateral spreading)
#---------------------
# max_z:
# Energy-Line-Height Limit (can be interpreted as velocity limit)
# max_v = sqrt(max_z*19.62)
# typical values:
#   - Avalanche:   ~270 m ... ~72 m/s
#   - Rockfall:    ~130 m ... ~50 m/s
#   - Debris-flow:  ~12 m ... ~15 m/s
#---------------------
alpha = 26
exp = 8
flux_threshold = 3.0e-4
max_z = 185


#++++++++++++ Use a dynamic u_max Limit
# Requires an additional tif-file containing the uMax  (in m/s)
# or zDeltaMax (m) Limits
# in every cell where a release cell is.
# the paths for each release cells are calculated with these uMax values
# (computed to z_delta, similar to the max_z) or zDelta values.
# In varUmaxParameter the parameter (uMax in m/s or zDeltaMax in m)
# provided is given.
variableUmaxLim = True
varUmaxParameter = uMax

#++++++++++++ Use a dynamic alpha angle
# Requires an additional tif-file containing the alpha angles
# in every cell where a release cell is.
# The paths for each release cells are calculated with these alpha angles
variableAlpha = True

#++++++++++++ Use a dynamic exponent
# Requires an additional tif-file containing the exponents
# in every cell where a release cell is.
# The paths for each release cells are calculated with these exponent
variableExponent = False

#++++++++++++ Use Forest Information
# NOTE AH 20240408: Dummy settings for Forest Interaction
# The forest implementation should mimick/reproduce the
# one from the "foreste_detrainment" branch in the avaframe/FlowPy repo
# which is partly described in D'Amboise et al. (2021)
#
# Forest-Interaction is only used if 'forest' is set to 'True'
#++++++++++++
forest = True

#++++++++++++
# Type of Forest-Interaction Model to use (only works in conjunction with forest = True!)
# valid choices:
#
#     * 'forestFriction' (D'Amboise et al., 2021) - use added friction on forest Pixels
#            forest-Raster (set in 'forestPath') is assumed to have values between
#            0 (no Forest) and 1 (full protective function).
#        model behavior is governed by 'maxAddedFrictionFor', 'minAddedFrictionFor'
#        and 'velThForFriction'
#
#     * 'forestDetrainment' (D'Amboise et al., 2022?) - added friction and detrainment on forested Pixels
#            forest-Raster (set in 'forestPath') is assumed to have values between
#            0 (no Forest) and 1 (full protective function).
#        model behavior is governed by 'maxAddedFrictionFor', 'minAddedFrictionFor'
#        and 'velThForFriction', 'maxDetrainmentFor', 'minDetrainmentFor', 'velThForDetrain'
#
#     * 'forestFrictionLayer' - provide Layer with local alpha / local delta-Alpha on forested pixels / for all pixels in
#        the domain
#            forest-Raster (set in 'forestPath') is assumed to have values between 0° (no friction) and 90° (inf. friciton)
#        forest-Raster is either interpreted as 'absolute' or 'difference'
#            'absolute'   - absolute 'alpha' values are used on forested pixels (all pixels with values > 0)
#            'relative' - 'alpha' values are interpreted as additional friction on forested pixels (all pixels with
#                          values > 0)
#++++++++++++

# ['forestFriction', 'forestDetrainment', 'forestFrictionLayer']
forestModule = forestFriction
# ForestInteraction gives an additional output layer for the amount of forested cells
# a path ran through
# (now implemented, only when forest = True) -> TODO: we dont require a forestModule to compute
# for ForestInteraction Layer, but we need to read in the Forest - Layer (requires forest = True)
forestInteraction = True

#++++++++++++ Forest added Friction
# These are the parameters for the "add friction on forested cells"-approach
# described in D'Amboise et al. (2021)
#
# maxAddedFrictionFor [°]: maximum increase of Alpha angle/basal friction on forested cells
# minAddedFrictionFor [°]: minimum increase of Alpha angle/basal friction on forested cells
# velThForFriction [m/s]: velocity threshold for forest-friction effect
#++++++++++++

maxAddedFrictionFor = 21
minAddedFrictionFor = 0
velThForFriction = 45

#++++++++++++ Forest Detrainment
# These are the parameters for the "forestDetrainment"-approach - D'Amboise et al. (2022??)
# The idea is to remove 'virtual mass' (aka 'flux' in Flow-Py) from the modeled flow/process
# on forested pixels in dependency of FSI and local z_delta
#
# maxDetrainmentFor [°]: default set to '0' (i.e. no detrainment) - foreste_detrainment val:
# minDetrainmentFor [°]: default set to '0' (i.e. no detrainment) - foreste_detrainment val:
# velThForDetrain [m/s]: velocity threshold for forest-detraiment effect # default set to '0' (i.e. no detrainment) - foreste_detrainment val:
#++++++++++++

maxDetrainmentFor = 0
minDetrainmentFor = 0
velThForDetrain = 0

#++++++++++++ ForestFrictionLayer
# The forest layer defines the alpha angle in forested areas.
# If forestFrictionLayerType = relative, forest layer values are added to the global alpha angle.
# e.g. if alpha = 24° and value on forest cell is 5°, then effective  local alpha of 24° + 5° = 29° will be used.
# -------------------
# If forestFrictionLayerType = absolute, forest layer values are used as alpha angle,
# if they are larger than the global alpha angle.
# e.g. if global alpha = 24° and value provided in the forestFrictionLayer on a cell is 35°,
# then local alpha of 35° will be used.
#++++++++++++

# ['absolute', 'relative']
forestFrictionLayerType = absolute

# skip Forest Effect (added forest friction) for first x meters (calculated in 3D - XYZ)
# should allow an initial acceleration phase of processes starting in or directly above
# dense forests (these would in many cases stop otherwise)
# if e.g. skipForestDist = 40, no added forestFriction will be assumed until 40 m 3D-distance
# along the path from the startCell.
skipForestDist = 0


#++++++++++++ Parameters for Tiling
# tileSize: size of tiles in x and y direction in meters (if total size of) x
#           or y of input DEM is larger than tileSize, then the input raster
#           layers are tiles
# tileOverlap: overlap between single tiles in m (5 km is rather conservative)
#---------------------------------------

#++++++++++++ Calculate with generations
# If calcGenerations = True, a different order of cells in a path are calculated.
# The results can vary when computing with generations.
# Additionally, the generation (iteration step) can be derived, which is required
# to get thalweg information.
calcGeneration = True
# set to True to compute thalwegs and save them as pickle files
# To compute thalwegs, calcGeneration needs to be set to True.
calcThalweg = True
# You can choose how the thalweg is computed: with the center of energy, center of flux and/or
# center of zdelta. The format should be: thalwegCenterOf = ['zdelta','energy', 'flux']
thalwegCenterOf = ['flux']
# The saved variables can be chosen in thalwegVariables. Possible variables are.
# ['col', 'row', 'x', 'y', 'flux', 'fluxSum' 'flowEnergy', 'altitude', 'travelLength', 'zDelta', 'gamma', 'flowEnergyArray', 'zDeltaArray', 'fluxArray']
# the arrays contain the respective values of the path and need much memory
thalwegVariables = ['x', 'y', 's', 'zDelta']
# if thalwegReleaseArea is True, one thalweg is computed for each continuous release area
# (in Inputs/RELID a raster file needs to be provided containing the release area ID)
# if thalwegReleaseArea is False, a thalweg is computed for each startcell
thalwegReleaseArea = True
# only compute thalweg variable x and y to safe RAM
thalwegSaveRam = True


tileSize = 15000
tileOverlap = 5000

#++++++++++++ Parameters for CPU usage/multiprocessing
# Recommended to leave at default values unless performance has to be
# tweaked/optimized (e.g. for application on dedicated machines, maxing out
# computational resources)
#
# procPerCPUCore: number of processer per core for multiprocessing
#                default value = 1 (it is recommended not to change this value
#                unless you want to max. out CPUs, which might come at the cost
#                of RAM comsumption!!!)
# chunkSize: tbd.
# maxChunks: Maximum number of single tasks for multiprocessing, if set too high
#           this can max out RAM and lead to unexpected behavior (in this case
#           probably an infinite loop --> you see it in the .log if this happens)
#           On machines with a lot of CPUs and RAM this value might be set higher ...
#++++++++++++
procPerCPUCore = 1
chunkSize = 50
maxChunks = 500

# define the different output files that are written to disk
# default = 'zDelta|cellCounts|travelLengthMax|fpTravelAngleMax'
# additional options:
#                    slTravelAngle
#                    flux
#                    zDeltaSum
#                    routFluxSum
#                    depFluxSum
#                    travelLengthMin
#                    fpTravelAngleMin
#                    relIdPolygon
#                    relIdCount
# if forestInteraction: forestInteraction is automatically added to outputs
# if infra: backCalculation is automatically  added to output
# if relVolMin or relVolMax is in outputFiles, the Volume of the PRA should be provided in the raster file in the REL folder
# if relIdCount or relIdPolygon is in outputFiles, the ids of the PRAs should be provided in the raster file in the RELID folder
outputFiles = zDelta|cellCounts|travelLengthMax|fpTravelAngleMax



[mod3Map_regionalThalwegAnalysis_override]
# use default regionalThalwegAnalysis config as base configuration (True)
# if False and local is available use local
defaultConfig = True


# flags which plots should be saved:
plotStatisticBoxplot = True
plotStatisticScatterPlot = True
plotAllThalwegLocations = True
# these plots are done for each thalweg
plotThalwegLocation = False
plotThalweg2D = False
plotThalwegAltitude = False

# The simulation hash of the simulation that is analysed
# If only one results folder with a simhash exists, this is used.
simHash =

# Module name of the simulation that is analysed (the analysis is tested for com4FlowPy)
modName = com4FlowPy

# column and row number (x and y  coordinate of raster) of the starting cell of the thalweg/path
# if (startRow or startCol) and relId is empty, for all thalwegData (with relating center of variable) are plotted
startRow =
startCol =
relId =

# output variable that is plotted (of whole simulation)
plotVariable = zdelta
# which center of is used
# possible:CoF (center of flux, default), CoZd (center of zdelta), CoE(center of energy)
# if empty all files are plotted
centerOfVariable = CoF

# If True, all thalwegs are represented in the field plot (upper panel)
thalwegPra = True
colorPra = 6900D1

# Avalanche size is only for the plot title
avalancheSize =

# variable that is used for statistic boxplots over all thalwegs
# possible: travelLengthMax, velocity, impressure, (the extended values within the process path are used)
# travelLengthAveraged, velocityAveraged, impressureAveraged, zdeltaAveraged (averaged values are used: without thalweg extension)
# alphaIn, velocityMaxIn, zdeltaMaxIn  (the input data)
# relArea (areas of release areas)
# "averaged" means that the averaged thalweg values are used (not read from raster along thalweg)
statisticVariable = travelLengthMax

# if plotLogScale is True the y axis of the statistic boxplots is logarithmic
plotLogScale = False

# if plotAllThalwegLocations is True or plotThalweg2D is True,
#choose if the extended thalwegs or the aeraged thalwegs are plotted
2DExtendedThalwegs = False

# if averagedZdelta is True, for thalweg data the averaged values are used for zdelta (and velocity and impact pressure)
# if averagedZdelta is False, the data is read from the result zdelta raster
# (be aware that this is the maximum of all overlayed flow paths)
averagedZdelta = True

# density of avalanche (used for computing impact pressure) in kg/m³
rho = 200

boxplotYlimMin =
boxplotYlimMax =


# colors for the sizes
colorSize1 = 0096FF
colorSize2 = 00FF00
colorSize3 = FFD500
colorSize4 = FF0000
colorSize5 = AA00FF

# boundaries for sizes
# ------ technical scheme ---------------
# for runout length [m] - technical scheme
travelLengthSize1Max = 52
travelLengthSize2Max = 263
travelLengthSize3Max = 889
travelLengthSize4Max = 2000

# for impact pressure [kPa] - technical scheme
impressureSize1Max = 18
impressureSize2Max = 56
impressureSize3Max = 178
impressureSize4Max = 562

# for release area [m²] - technical scheme
relAreaSize1Max = 500
relAreaSize2Max = 2500
relAreaSize3Max = 12500
relAreaSize4Max = 62500

# for deposition volume [m²] - technical scheme
depVolumeSize1Max = 1000
depVolumeSize2Max = 10000
depVolumeSize3Max = 100000
depVolumeSize4Max = 1000000

# ------ communication scheme ---------------

# for runout length [m] - communication scheme
travelLengthSize1MaxCom = 50
travelLengthSize2MaxCom = 250
travelLengthSize3MaxCom = 900
travelLengthSize4MaxCom = 2000

# for impact pressure [kPa] - communication scheme
impressureSize1MaxCom = 20
impressureSize2MaxCom = 50
impressureSize3MaxCom = 200
impressureSize4MaxCom = 500

# for release area [m²] - communication scheme
relAreaSize1MaxCom = 500
relAreaSize2MaxCom = 2500
relAreaSize3MaxCom = 12500
relAreaSize4MaxCom = 62500

# for deposition volume [m²] - communication scheme
depVolumeSize1MaxCom = 1000
depVolumeSize2MaxCom = 10000
depVolumeSize3MaxCom = 100000
depVolumeSize4MaxCom = 1000000


# ana5Utils_DFAPathGeneration_override

# extension method at the top
# option 0: take the highest particle in the release
# option 1: find the point that will lead to the longest runout
# option 2: find path depending on flow direction
extTopOption = 2

# the thalweg is re-sampled
# re-sampling step size is defined resampleDistance = nCellsResample x cellSize)
nCellsResample = 2
# Degree of the spline for splprep.
kResample = 1

# when extending the path at the bottom, extend path in
# the direction extracted form the last points of the path
# (all points at a distance nCellsMinExtend x cellSize < distance < nCellsMaxExtend x cellSize
# from the end)
nCellsMinExtend = 1
nCellsMaxExtend = 20
# this value needs to be chosen in accordance with nCellsResample (if nCellsMaxExtend < nCellsResample no points
# might be found for the path extension process)

# for the extrapolation at the bottom, add factBottomExt * sMax to the path (and then check if the extension
# is on the DEM, if not iterate by dichotomy until we find a point on the topography or reach a maximum
# iteration number (integer, in this case we pick the last point found inside the dem)
# or precision (nBottomExtPrecision * cellSize))
factBottomExt = 0.5
maxIterationExtBot = 10
nBottomExtPrecision = 10