# Parameters for computing dynamic mobility parameters

[avaSIZE]
# Rel vol size dependent parametrization for
# > dry:
sizeMax = 5
alphaSize2 = 32
deltaAlpha = 3
uMaxSize2 = 8
deltaUMax = 18
expCoeff = 75
expBase = 0.64
constantExp = True
constantExpValue = 12
constantPraThickness = True
praThickness = 1

# Rel vol size dependent parametrization shift for
# > wet:
alphaDependendTemperature = True
sizeShiftAlpha = 0.5
sizeShiftUmax = -0.75
sizeShiftExp = 0.5

# Results to size
resParamsToSize =

# snow climate (not used ATM)
D0 = 0
deltaD = 0.001
constantTemperature = True
Tcons = -11
T0 = 0
deltaT = -0.01
TCold = -11
TWarm = -1

[avaPARAMETER]
flowTypes = dry, wet
sizeRange = 2-5

[PLOT]
# only elevation or ARel can be modified
elevationMin = 1000
elevationMax = 1000
ARelMin = 1000
ARelMax = 125000
plotExponent = False
d = 1
theta = 30