# Parameters for PRA Delineation using the method from Veitinger et al. 2016

[MAIN]
customPaths = False

[praDELINEATION]
forestType = pcc
saveAllThresholds = False
singleThreshold = 0.30
radius = 6
prob = 0.5
winddir = 0
windtol = 180

